sudo: required
language: generic
services: docker
before_install:
  - echo "start creating an image width docker file"
  - docker build -t james/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true james/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"